# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c3286b264ecfe2d7fad2cdf5befd2d1"
name = "discount"
handle = "discount-153"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "learntest12324.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
